[package]
name = "dado3d"
version = "0.1.0"
description = "Dado3D desktop shell"
authors = ["Arkanus"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
